authors: [eccentric_nz]
main: me.eccentric_nz.tardisshop.TARDISShopPlugin
name: TARDISShop
description: A simple shop plugin for TARDIS items
version: ${project.version}
api-version: 1.17
load: POSTWORLD
depend: [TARDIS,Vault]
soft-depend: [TARDISWeepingAngels]
website: https://github.com/eccentricdevotion/TARDISShop/
permissions:
  tardisshop.use:
    description: Allows a player to buy items from a TARDIS Shop.
    default: op
  tardisshop.admin:
    description: Allows a player to set up a TARDIS Shop.
    default: op
commands:
  tardisshop:
    aliases: [tshop]
    description: Adds and removes TARDISShop items.
    usage: "Usage: /<command> (add|remove|update) <item>"
    permission: tardisshop.admin
    permission-message: "You need the permission '<permission>' to use this command!"
